[project]
name = "project-thesis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
  "ipywidgets>=8.1.8",
  "jupytext>=1.19.3",
  "matplotlib>=3.10.9",
  "numpy>=2.4.6",
  "pandas>=3.0.3",
  "pytorch3d==0.7.9+pt2.10.0cu128",
  "seaborn>=0.13.2",
  "torch==2.10.0",
  "torchvision==0.25.0",
  "torch-geometric>=2.8.0",
  "tqdm>=4.68.2",
  "pyyaml>=6.0.3",
  "pyvista[jupyter]>=0.48.4",
  "opencv-python>=5.0.0.93",
  "fiftyone>=1.19.0",
  "rfdetr[loggers,train]>=1.9.1",
]

[dependency-groups]
dev = [
  "ipykernel>=7.2.0",
]

[tool.uv.sources]
torch = [
  { index = "pytorch-cu128", marker = "sys_platform == 'win32'" },
]
torchvision = [
  { index = "pytorch-cu128", marker = "sys_platform == 'win32'" },
]
pytorch3d = [
  { index = "miropsota", marker = "sys_platform == 'win32'" },
]

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[[tool.uv.index]]
name = "miropsota"
url = "https://miropsota.github.io/torch_packages_builder"
