dataset_path_2d: "data/Teeth2D"
dataset_path_3d: "data/Teeth3DS+"
train_split: "data/train.txt"
test_split: "data/test.txt"
class_ids: [0, 
  11, 12, 13, 14, 15, 16, 17, 18, 
  21, 22, 23, 24, 25, 26, 27, 28, 
  31, 32, 33, 34, 35, 36, 37, 38, 
  41, 42, 43, 44, 45, 46, 47, 48]
# a dict used to remap class ids internally for the following reasons:
# - fiftyone: pixel value 0 is reserved for "background"
# - COCO: dataset category IDs are 1-based
# TODO: provide full class id map to avoid special handling in teeth2d_dataset_importer.py and just use mapped_class_ids?
class_id_map:
  0: 1 # remap class id 0 to class id 1
2d_projection:
  image_size: [512, 512]
  background_value: 0
  distance: 80
  fov: 60
  views: # each view is [elevation, azimuth]
    - [0, 0]    # top down
    - [-90, 0]  # front center
    - [90, 0]   # back center
    - [-60, 0]  # top down front diagonal center
    - [60, 0]   # top down back diagonal center
    - [0, -45]  # top down front diagonal left
    - [0, 45]   # top down front diagonal right
    - [60, -45] # bottom up back diagonal left
    - [60, 45]  # bottom up back diagonal right
    - [0, -90]  # left side
    - [0, 90]   # right side
