# path definitions are relative to repository root
best_model_chkpt_path: "output/rf_detr_train/20260912_010327/Teeth2D/checkpoint_best_ema.pth"
data_path: "data"
data_path_projections: "data/Projections"
dataset_path_2d: "data/Teeth2D"
dataset_path_3d: "data/Teeth3DS+"
dataframe_eda: "data/eda.csv"
output_path: "output"
output_rf_detr_train: "output/rf_detr_train"
temp_path: "temp"

class_ids: [0, 
  11, 12, 13, 14, 15, 16, 17, 18, 
  21, 22, 23, 24, 25, 26, 27, 28, 
  31, 32, 33, 34, 35, 36, 37, 38, 
  41, 42, 43, 44, 45, 46, 47, 48]
# a dict used to remap class ids internally for the following reasons:
# - fiftyone: pixel value 0 is reserved for "background"
# - COCO: dataset category IDs are 1-based
# TODO: provide full class id map to avoid special handling in teeth2d_dataset_importer.py and just use mapped_class_ids?
class_id_map:
  0: 1 # remap class id 0 to class id 1

2d_projection:
  # common resolution values for RF-DETR-Seg models:
  # https://rfdetr.roboflow.com/latest/learn/train/training-parameters/#resolution-parameters
  # RF-DETR-Seg-N: 312x312
  # RF-DETR-Seg-S: 384x384
  # RF-DETR-Seg-M: 432x432
  # RF-DETR-Seg-L: 504x504
  # RF-DETR-Seg-XL: 624×624
  # RF-DETR-Seg-2XL: 768×768
  image_size: [432, 432]
  background_value: 0
  distance: 80
  fov: 60
  # views for projection rendering, each view is [elevation, azimuth]
  # - tooth id (FDI) is defined by it's quadrant (1 to 4) and and position from the midline (1 to 8), appearance less relevant/distinguishable
  # - make sure the view allows keeping track of spatial context (where tooth is located relative to jaw)
  # - make sure the view includes contextual anchors (e.g. curvature of the jaw line)
  views: 
    - [0, 0]    # top down
    - [-60, 0]  # top down front diagonal center
    - [0, -45]  # left side flat
    - [0, -75]  # left side steep
    - [0, 45]   # right side flat
    - [0, 75]   # right side steep
    - [60, 0]   # bottom up back diagonal center
    - [60, -45] # bottom up back diagonal left
    - [60, 45]  # bottom up back diagonal right
